### ISSUE TITLE
IndexOutOfBoundsException When Filtering ModelAbstractItem

### ISSUE THREAD

**Issue by StuStirling** [mikepenz/FastAdapter#757] opened 2019-03-01 16:59 UTC
## About this issue

When filtering my items, I am experiencing an `IndexOutOfBoundsException`. This isn't every time but it is consistently crashing for certain search queries with the same data set (I cannot see any anything in the queries that would cause it however)

I have a data set of `PostItems` which extend `ModelAbstractItem`.

This is how I'm configuring the filter predicate:

```
postsAdapter.itemFilter.withFilterPredicate { item, constraint ->
            return@withFilterPredicate if (constraint == null) false
            else {
                val lowered = constraint.toString().toLowerCase()
                val meetsSearch = item.model.text.toLowerCase().contains(lowered) ||
                        item.model.title?.toLowerCase()?.contains(lowered) == true
                meetsSearch
            }
        }
```

Then to trigger the search I am just calling the `postsAdapter.filter(search)` method. 

Here is the exception: 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.padoq.android.develop.debug, PID: 23397
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:-1).state:2 androidx.recyclerview.widget.RecyclerView{5763cd5 VFED..... ......ID 0,0-1440,2187 #7f0a04e2 app:id/rv_lpv_recycler}, adapter:com.mikepenz.fastadapter.commons.adapters.FastItemAdapter@1fbc738, layout:androidx.recyclerview.widget.LinearLayoutManager@c371311, context:com.padoq.android.ui.padoq.PadoqViewActivity@8b02655
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1961)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1961)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1633)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
        at android.view.View.layout(View.java:19586)
E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

## Details
FastAdapter Library Version: 
```
implementation('com.mikepenz:fastadapter:3.3.0@aar') {
        transitive = true
    }
    implementation 'com.mikepenz:fastadapter-commons:3.3.0@aar'
```

Support library versions:
```
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.legacy:legacy-support-core-ui:1.0.0'
implementation 'androidx.legacy:legacy-support-v13:1.0.0'
implementation 'com.android.support:design:28.0.0'
```

Gradle Build tools: `classpath 'com.android.tools.build:gradle:3.3.1'`
Android Studio Version: `3.3.1`

**Comment by StuStirling** [comment] 2019-03-04 11:46
As a workaround, i found [this answer](https://stackoverflow.com/a/33985508/507313).

It involved turning off the `supportsPredictiveItemAnimations` and I did this by extending the `LayoutManager` and returning false for that method like so:

```
private class NpaLinearLayoutManager @JvmOverloads constructor(
            context: Context,
            orientation: Int = RecyclerView.VERTICAL,
            reverseLayout: Boolean = false) : LinearLayoutManager(context,orientation,reverseLayout) {
        override fun supportsPredictiveItemAnimations(): Boolean {
                return false
            }
    }
```

**Comment by mikepenz** [comment] 2019-03-04 12:14
Very interesting. thank you so much for the very detailed report. 

Is it somehow possible to reproduce this issue also in the sample app? 
or just with this very particular data set in your app?

**Comment by StuStirling** [comment] 2019-03-04 12:27
I'm not sure if it would be reproducable. I think it would be but I wouldn't be able to say what exact combination caused it.

**Comment by mikepenz** [comment] 2019-06-07 22:00
I am closing this now as it seems to be not a general issue. Please report back with more details if it is still causing problems

**Closed by mikepenz** 2019-06-07 22:00 UTC
Labels: question
