### ISSUE TITLE
Endless scrolling - onLoadMore not being called

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#497] opened 2017-07-28 12:59 UTC
I have two recycler view inside a nested scrollview. The second one is implemented with Fast Adapter Endless scrolling. The endless scroll does not work if I setNestedScrollingEnabled(false) to my recycler view.

```
<android.support.v4.widget.NestedScrollView
    android:id="@+id/nestedScrollView"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:isScrollContainer="true"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        android:orientation="vertical"
        android:paddingBottom="90dp"
        android:clipToPadding="false">

        ...

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recentlyPlayedList"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingTop="8dp"/>

        ...

        <android.support.v7.widget.RecyclerView
            android:id="@+id/othersFootbuddiesList"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingTop="8dp"/>

    </LinearLayout>
</android.support.v4.widget.NestedScrollView>
```

Here's the Java code:

```
   private FooterAdapter<ProgressItem> footerAdapter;

    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

	...

        mFastItemAdapter = new FastItemAdapter<>();
        footerAdapter = new FooterAdapter<>();

        ...

        othersFootbuddiesList.addOnScrollListener(new EndlessRecyclerOnScrollListener(footerAdapter) {
            @Override
            public void onLoadMore(int currentPage) {
                footerAdapter.clear();
                footerAdapter.add(new ProgressItem().withEnabled(false));
                //simulate networking (5 seconds)
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        footerAdapter.clear();
                        for (int i = 1; i < 16; i++) {
                            mFastItemAdapter.add(mFastItemAdapter.getAdapterItemCount(), new ProfileOthersFootbuddiesAdapter()
                                    .withName("Filipi" + i)
                                    .withPosition(getString(R.string.attack_code))
                                    .withInitial(App.getNameInitials("Filipi"))
                                    .withPaid(true)
                                    .withUserId("321"));
                        }
                    }
                }, 5000);
            }
        });

        mFastItemAdapter.add(Arrays.asList(...);

        return view;
    }
```

**Comment by guuilp** [comment] 2017-07-28 13:33
If I remove this line, it works:

`othersFootbuddiesList.setNestedScrollingEnabled(false);`

But I can't remove it, otherwise the scroll is not smooth.

**Comment by guuilp** [comment] 2017-07-28 13:53
If I remove this line of code, it works:

`othersFootbuddiesList.setNestedScrollingEnabled(false);`

But I cant't remove it, otherwise the scroll won't be smooth at all.

**Comment by FabianTerhorst** [comment] 2017-07-28 15:20
The current way the endless scroll listener is implemented does not support nested scrolling. We are always open for an pull request.

**Comment by mikepenz** [comment] 2017-07-29 09:28
@guuilp as @FabianTerhorst already pointed out correctly nested scrolling is not supported. The ScrollListener we offer is just a nice `addon` and not really a core component of the library. You should be able to use any scroll listener which offers this functionality (as long as it does not require a specific adapter) 

We are always glad to get a PR to improve such elements.

I might close this issue in the upcoming days as the provided listener works as intended.

**Closed** 2017-07-29 20:53 UTC
Labels: question
