### ISSUE TITLE
IndexOutOfBoundsException when using FastAdapterDiffUtil.calculateDiff

### ISSUE THREAD

**Issue by mikezliu** [mikepenz/FastAdapter#878] opened 2020-03-04 01:46 UTC
## About this issue

- Briefly describe the issue

I'm hitting an IndexOutOfBoundsException when using calculateDiff and the difference results in items being removed. My usage is as follows. Any ideas what might be going on?

When I attached a breakpoint, it crashes after the line 'FastAdapterDiffUtil.calculateDiff(....' and the subscribe block is not executed

```
.observeOn(Schedulers.computation())
.map { 
  // Create a new list of items (these are all new objects inside a new list)...
}
    .map { newItems ->
        FastAdapterDiffUtil.calculateDiff(
                itemAdapter,
                newItems,
                diffCallback)
    }
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe { diff ->
                FastAdapterDiffUtil[itemAdapter] = diff
            }
```

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mikepenz.fastadapter.utils.DefaultItemListImpl.get(DefaultItemListImpl.kt:23)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.getAdapterItem(ModelAdapter.kt:157)
        at com.mikepenz.fastadapter.FastAdapter.getItem(FastAdapter.kt:500)
        at com.mikepenz.fastadapter.FastAdapter.getItemViewType(FastAdapter.kt:576)
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5978)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
```

- How can the issue be reproduced / sample code

See above for code

## Details
- [ 4.1.0 ] Used library version
- [ ] Used support library version
- [  ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ x ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues) -> yes I see similar issues, but they were closed with no repro / no resolution
- [ x ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ x ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ x ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ x ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikezliu** [comment] 2020-03-08 04:45
I debugged this issue a bit, in FastAdapter.kt I attached a breakpoint and see that it's crashing here:

`
    open fun getItem(position: Int): Item? {
        //if we are out of range just return null
        if (position < 0 || position >= globalSize) {
            return null
        }
        //now get the adapter which is responsible for the given position
        val index = floorIndex(adapterSizes, position)
        **return adapterSizes.valueAt(index).getAdapterItem(position - adapterSizes.keyAt(index))**
    }
`
 adapterSizes.keyAt(index) is 0 and position is also 0

**Comment by mikezliu** [comment] 2020-03-08 05:01
When I move FastAdapterDiffUtil.calculateDiff to be run on the main thread instead of background thread, there is no crash. Though the samples use calculateDiff on the background thread as I do. 

In calculateDiff I see that it's clearing and adding items to the adapter. Is it safe to do this on the background thread? In my previous RecyclerView code, I used DiffUtil in a background thread, but only modify the adapter on the main thread.

**Comment by mikezliu** [comment] 2020-03-08 05:50
After I remove step 1.b. from FastAdapter, the crash goes away - here is my commit: https://github.com/mikezliu/FastAdapter/commit/11fc8f60dd9f9bffaafdbd2c659c856649d7c213

I tested it a bit and didn't see any side effects. Maybe this is also related to some other IndexOutOfBoundsException like this one: https://github.com/mikepenz/FastAdapter/issues/642

**Comment by mikepenz** [comment] 2020-03-08 11:19
so the `FastAdapterDiffUtil` tries to simplify your implementation by taking away additional steps. This suites for many situations but. may not serve more complicated setups as yours seem to be. e.g. other parts may invalidating the view and the list data. 

So the FastAdapter tries to always do the setting / updating / notifying with simple utils for the user to make things easier, solve situations for users who would not think about doing this. 

Btw. the problem is gone with main thread as things can not happen async so the RC is not possible which would occur due to multiple threads modifying the data. 

In your case please either stop allowing other threads to modify in parallel, or only calculate the diff and set the changes yourself like you used to with additional code to ensure that you do not run into RCs

Thank you so much for your detailed information and steps. I think this may be very beneficial for others too!

**Comment by mikepenz** [comment] 2020-03-08 11:20
marking as good to know :) 

I hope this issue is resolved with this now :) 
If not please let me know if I can help you with anything else

**Closed by mikepenz** 2020-03-08 11:20 UTC
Labels: good to know, question
