### ISSUE TITLE
Items size not being adjusted on custom DPI settings

### ISSUE THREAD

**Issue by franciscofranco** [mikepenz/FastAdapter#82] opened 2016-03-18 19:43 UTC
I'm not sure this is something you can fix, or even something you can reproduce, but I'm using FastAdapter on this mutative design open source project and I had this one user describing a weird bug while using the adapter. Check here for the issue + video: https://github.com/liamspradlin/Phoebe/issues/5

Again, I'm not sure this is something on your side, just though of bringing it up. I can't reproduce on my stock-dpi devices (tried on all Nexus devices since the Galaxy Nexus, One Plus 2, One Plus X and Nextbit Robin).

**Comment by mikepenz** [comment] 2016-03-18 20:20
@franciscofranco I have the weird feeling that it may be related to the `ItemAnimator` or that it is caused by the `LayoutManager`. Perhaps from the `StaggeredGridLayoutManager` and a wrong messurement. 

I am pretty sure it is unrelated to the `FastAdapter` itself as the `Adapter` just provides the items, but does not handle positioning, nor animations. The items themself follow the `ViewHolder` pattern and just provide the general view, which is also unrelated to the positioning. 

You assumption that it may be the custom DPI could be true.

**Comment by mikepenz** [comment] 2016-03-21 19:37
@franciscofranco already found something new about this issue?

**Comment by franciscofranco** [comment] 2016-03-22 18:14
Not yet, haven't had the time yet. I'll contact you on Slack about it

**Comment by mikepenz** [comment] 2016-03-22 18:49
@franciscofranco ok fine.

**Comment by mikepenz** [comment] 2016-03-27 16:42
I think I can safely close this issue as I am pretty sure it is unrelated. If we find the root cause or a solution we can still answer it here.

**Closed by mikepenz** 2016-03-27 16:42 UTC
Labels: question
