### ISSUE TITLE
class cast exception with expandable item

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#719] opened 2018-08-30 11:52 UTC
## Details
- [3.2.8] Used library version
- [27.1.1 ] Used support library version
- [3.1.4 ] Used tooling / Android Studio version

## Checklist

- [V ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ V] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ V] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ V] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ V] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

## About this issue
i am implementing an expandable list with selection but when deselecting the last item (not the item in the last index, but the last item to be deselected) i get class cast exception saying that the sub item class cannot be cast into the parent class. the exception is only thrown when deselecting the last item, for example:
* list containing 10 items
* selecting items 1, 2, 3 - fine
* deselect item 1 and 3 - fine
* deselect item 2 - class cast exception

this is the parent
```
class EpisodeAdapterItem(episode: EpisodeEntity)
    : ModelAbstractExpandableItem<EpisodeEntity, EpisodeAdapterItem, EpisodeAdapterItem.ViewHolder, EpisodeAdapterSubItem>(episode)
```

this is the sub item
```
class EpisodeAdapterSubItem(private val descriptionHtml: String)
    : AbstractExpandableItem<EpisodeAdapterItem, EpisodeAdapterSubItem.ViewHolder, EpisodeAdapterSubItem>()
```

after a little investigating i found that in the library class `SelectExtension`, the method `public void deselect(Item item, int position, @Nullable Iterator<Integer> entries) ` is called twice (not sure sure why twice): once with `item` as the parent (everything is fine), and the second time with `item` as the subitem.
the exception is thrown in the line `mSelectionListener.onSelectionChanged(item, false);` because the selection listener is expecting `item` to be of the parent type, however the second time this method is trying to pass the sub item type which causes the exception.

why is the method `deselect` called twice once with parent and once with sub item? is this a bug? am i doing something wrong?

**Comment by mikepenz** [comment] 2018-08-30 12:42
potential duplicate of: https://github.com/mikepenz/FastAdapter/issues/703

**Comment by or-dvir** [comment] 2018-08-30 13:10
doesnt look like it... my problem does not relate to search/filtering and setting item animator to null does not resolve the issue.
however maybe the issue you mentioned in your comment on `onViewDetachedFromWindow()` method somehow causes both #703 **and** my issue... any news on this since July 24th (the date of your comment)? are you still working on it?

can you please confirm whether my class definitions for parent and sub item are ok?
both the parent and sub item have different type ids, but i am only setting identifier for the parent (which is the id of the model), whereas in the sub item class i am not doing anything related to identifier. could this be related to the crash somehow?
if it helps, the item is not expanded when deselecting it

**Comment by or-dvir** [comment] 2018-09-12 11:03
@mikepenz any news? this is an app breaking bug for me...

**Comment by mikepenz** [comment] 2018-09-14 18:04
@or-dvir I am so sorry. was on vacation in iceland for a week and had no chance to look at anything. 

I am still hoping that I can resolve the other ticket I linked you. just in case could you please create a sample app which showcases the problem or a branch to showcase the problem in the sample app, so I can hopefullly have a quicker look at it on the weekend?

**Comment by or-dvir** [comment] 2018-09-15 05:43
no worries. nothing to apologize for. i was just wondering whats going on...

by all means, go for the linked ticket first. it might be related.
about a sample app, i will do my best but i dont think it will be within the next week as i have some other projects i must finish.

**Comment by mikepenz** [comment] 2018-09-15 10:32
do you use the abstract expandable item for this? 

could it be that the reference of parent to childs might be not done properly?

**Comment by mikepenz** [comment] 2018-09-15 10:33
other than that I'd definitely need some sample to try to debug this. otherwise it's searching around in the dark :( sorry.

**Comment by or-dvir** [comment] 2018-09-16 06:26
my class definitions are as above. as far as i can tell they are fine... correct me if im wrong.
ill try to make a small sample app today

**Comment by or-dvir** [comment] 2018-09-16 07:31
@mikepenz please see this small [sample app](https://github.com/or-dvir/FastAdapterDeselectBug/tree/master/app/src/main/java/com/sample/fastadapterdeselectbug)

as mention above, the crash occurs when deselecting the last item (no the item in the last index, but the last item to be deselected)

steps to reproduce the crash:
1- select any item
2- deselect that item

**Comment by mikepenz** [comment] 2018-09-16 15:46
Ok now after seeing the problem, this one is actually rather easy described and solved. 

So the problem is that you have a `FastAdapter<EpisodeAdapterItem>`. That would mean it only accepts this type of items. Adding a sub child adapter holding other items might be allowed (due to the fact that generics are not really helpful to prevent such a usage), but it will crash during runtime. 

Instead you need to use a type for the FastAdapter which is valid across all child items you will hold in the adapter. 
It might be that your implementation has a combined parent type, or it might be `ModelAbstractItem`, or `AbstractItem`, but one thing which is always true is the `IItem` interface. 

So if you adjust the `FastAdapter` to be `FastAdapter<*>` it will allow all kind of items and it will not lead to the crash. 

-------------------------

To be a bit more specific. 
The FastAdapter is the global managing instance which wraps like an umbrella around all child adapters, thus the FastAdapter must accept all child items you might add. 

If you have a `FastAdapter<*>` it does not matter how many different `ItemAdapter`, `ModelAdapter` with all sorts of different items you add. 
but if you have a `FastAdapter<FancyItem>` it will only be able to handle adapters with this item type (`ItemAdapter<FancyItem>` or any item which extends `FancyItem` basically `ItemAdapter<T extends FancyItem>`)

Here's your code adjusted to make it work. (this btw. might not be the best thing, there are possibly other variants to have for example `FastAdapter<IItem<*, *>>` but having `FastAdapter<*>` worked during testing :D)

```java
class ActivityMain : AppCompatActivity() {
    private lateinit var mAdapterEpisodes: ModelAdapter<EpisodeEntity, EpisodeAdapterItem>
    private lateinit var mAdapterRv: FastAdapter<*>
    private lateinit var mActionModeHelper: ActionModeHelper<*>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        rv.apply {
            addItemDecoration(DividerItemDecoration(this@ActivityMain, DividerItemDecoration.VERTICAL))
            layoutManager = LinearLayoutManager(this@ActivityMain, RecyclerView.VERTICAL, false)
            setupAdapter()
            adapter = mAdapterRv
        }

        mAdapterEpisodes.add(
                EpisodeEntity("item 1"),
                EpisodeEntity("item 2"),
                EpisodeEntity("item 3"),
                EpisodeEntity("item 4"),
                EpisodeEntity("item 5"),
                EpisodeEntity("item 6"),
                EpisodeEntity("item 7"),
                EpisodeEntity("item 8"),
                EpisodeEntity("item 9"),
                EpisodeEntity("item 10")
        )
    }

    private fun setupAdapter() {
        mAdapterEpisodes = ModelAdapter { episode ->
            val subItem = listOf(EpisodeAdapterSubItem("${episode.text} sub item"))
            val finalItem = EpisodeAdapterItem(episode)
            finalItem.withSubItems(subItem)

            finalItem
        }

        mAdapterRv = FastAdapter<IItem<*, *>>().addAdapter(0, mAdapterEpisodes as IAdapter<IItem<*, *>>)
                .withSelectable(true)
                .withSelectOnLongClick(true)
                .withMultiSelect(true)
                .withOnPreClickListener { v, adapter, item, position ->
                    if (item is EpisodeAdapterItem) {
                        //if actionMode is active, it means the the users' clicks
                        //should select another item and NOT expand it
                        item.autoExpand = !mActionModeHelper.isActive
                    }
                    mActionModeHelper.onClick(item) ?: false
                }
                .withOnLongClickListener { v, adapter, item, position ->
                    //this is just so selecting an item will not trigger "onClick()"
                    true
                }
                .withOnPreLongClickListener { v, adapter, item, position ->
                    //if we have no actionMode we do not consume the event
                    mActionModeHelper.onLongClick(this, position) != null
                }
                .withSelectionListener { item, selected ->

                    //NOTE:
                    //the "selected" parameter is the state of the item AFTER
                    //the selection/de-selection

                    val numSelected = mAdapterRv.selected.size

                    //when selecting our first item on the list,
                    //collapse all expanded items.
                    //this will make it easier for the user to select more items without having
                    //to scroll past the expanded items (which may be long)
                    if (numSelected == 1)
                        mAdapterRv.collapseAll()

                    //NOTE:
                    //this if-else statement makes it so that
                    //once an item is selected, selecting other items could be done via
                    //a regular click (tap).
                    //once all items are de-selected, re-enable long click
                    //for selecting items

                    if (selected)
                        mAdapterRv.withSelectOnLongClick(false)
                    else if (numSelected == 0)
                        mAdapterRv.withSelectOnLongClick(true)
                }

        (mAdapterRv as FastAdapter<IItem<*, *>>?)!!.addExtension(ExpandableExtension<IItem<*, *>>()
                .withOnlyOneExpandedItem(true))

        mActionModeHelper = ActionModeHelper(mAdapterRv,
                R.menu.context_menu,
                object : ActionMode.Callback {
                    override fun onActionItemClicked(mode: ActionMode,
                                                     item: MenuItem): Boolean {
                        mode.finish()
                        return true
                    }

                    override fun onCreateActionMode(mode: ActionMode,
                                                    menu: Menu): Boolean {
                        return true
                    }

                    override fun onPrepareActionMode(mode: ActionMode?,
                                                     menu: Menu?): Boolean {
                        return false
                    }

                    override fun onDestroyActionMode(mode: ActionMode?) {
                        /*do nothing*/
                    }
                })
    }
}
```

**Closed** 2018-09-16 15:46 UTC
Labels: question

**Comment by or-dvir** [comment] 2018-09-17 09:28
thank you mike for this great explanation!
after reading it i have a few follow up questions if i may:
1) in the class `SelectExtension`, the method `public void deselect(Item item, int position, @Nullable Iterator<Integer> entries)` is called twice. once for sub item and once for parent item. i assume this is because both of those can be selectable. however, i specifically set my subitem to **not** be selectable. so why is this method still called? i dont think this method should be called on items which are not selectable as this will trigger the selection listener for items which are not selectable (which in my case caused the crash) and could probably lead to other bugs.
2) why is this only happening for the last item? i would expect it to be the same logic for every item that is deselected. is this by design? a bug?
3) simply using `FastAdapter<*>` doesnt seem right... not very object oriented. i would imagine i should use the "highest" object which is shared for both the parent and the child. am i correct? do you have an official recommendation on which type to use?
3.1. i believe that using `FastAdapter<*>` would also lead to future problems
4) please add some explanation of this (`FastAdapter` need to be of type shared for parent and sub item) in the readme file

**Comment by mikepenz** [comment] 2018-09-17 09:32
1.) making an item not selectable will only prevent the user not selecting it, you can very easily still select it programatically. the programmatic selecting/deselecting is always valid. 
2.) in the sample you provided it happened for all items
3.) exactly. so if you have a common type of your items you can use that. in the end the `IItem` is always the main thing true for all. so I believe (not sure if that's 100% right for kotlin) `*` would just mean that you can add all elements which implement `IItem` (as this type is defined in the FastAdapter generic definition. 
4.) the readme does not go up to type safe usage. it uses a `FastAdapter` without a type. so it is not needed there. The sample showcases it in the multi type samples :)

**Comment by mikepenz** [comment] 2018-09-17 09:35
but as this is open source. I am happy to take a PR to add this into the FAQ section

**Comment by or-dvir** [comment] 2018-09-17 11:19
1) ah. i understand.
2) i dont know how many tests you did, but it only crashes when deselecting the last item. for example if i have items 1, 2 and 3 selected, deselecting items 2 and 3 works perfectly fine but deselecting item 1 causes a crash. so why doesnt it crash when deselecting items 3 and 2?
4) in the sample app (`ExpandableSampleActivity`) `parent`, `subItem`, `subSubitem`, and subSubSubItems are all of the same type (`SimpleSubExpandableItem`)

**Comment by or-dvir** [comment] 2018-10-08 10:45
## SOLUTION
the "trick" (as mentioned by mike) is to make the parent and sub items the same type (which in my case is `AbstractExpandableItem`).
for convenience, i defined this wrapper class to save me from typing `<*,*,*>` all the time
```
abstract class MyExpandableItem<VH: RecyclerView.ViewHolder>
    : AbstractExpandableItem<EpisodeAdapterItem, VH, EpisodeAdapterSubItem>()
```
* this wrapper class is not mandatory and may change according to your own project.

then i went ahead and changed the definition of my parent and sub items
```
//old
class EpisodeAdapterItem(episode: EpisodeEntity)
    : ModelAbstractExpandableItem<EpisodeEntity, EpisodeAdapterItem, EpisodeAdapterItem.ViewHolder, EpisodeAdapterSubItem>(episode)
//new
class EpisodeAdapterItem(private val model: EpisodeEntity)
    : MyExpandableItem<EpisodeAdapterItem.ViewHolder>()
```
```
//old
class EpisodeAdapterSubItem(private val descriptionHtml: String)
    : AbstractExpandableItem<EpisodeAdapterItem, EpisodeAdapterSubItem.ViewHolder, EpisodeAdapterSubItem>()
//new
class EpisodeAdapterSubItem(private val descriptionHtml: String)
    : MyExpandableItem<EpisodeAdapterSubItem.ViewHolder>()
```
now in my Activity which holds the adapter i made the following changes:

```
//old line
private lateinit var mAdapterEpisodes: ModelAdapter<EpisodeEntity, EpisodeAdapterItem>
//new line
private lateinit var mAdapterEpisodes: ModelAdapter<EpisodeEntity, MyExpandableItem<*>>

//old line
private lateinit var mAdapterRv: FastAdapter<EpisodeAdapterItem>
//new line
private lateinit var mAdapterRv: FastAdapter<MyExpandableItem<*>>
```
* in case you use `ActionModeHelper`, don't forget to make the same change there.
* depending on your implementation, this may (and probably will) require some similar changes in other parts of your code
