### ISSUE TITLE
Issues with expandable items (wrong items are collapsed with mutli level items)

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#880] opened 2020-03-15 12:35 UTC
## About this issue

**Issue**

When I have expandable items (each level implements `IExpandable` and all use auto expand) that look like following:

 - Top 1
   - Sub 1.1
     - SubSub 1.1.1
     - SubSub 1.1.2
     - SubSub 1.1.3
   - Sub 1.2
 - Top 2

And I click `Top 1`, then `SubSub 1.1.2` and `SubSub 1.1.3` are not removed. Seems like FastAdapter does not sum up all sub items (including nested ones) when it collapses a parents items but only direct children.

**Note**

I found out that `isOnlyOneExpandedItem` in the expandable extension only works at the lowest level (at Sub Sub level in the example above) - it would be nice to allow one expanded item at each level only as well, this was actually what I was expecting.

## Details

- Used library version: 5.0.0
- android x recyclerview: 1.1.0

Setup looks like following:

    fastAdapter = FastAdapter.with(itemAdapter)
                .withSavedInstanceState(savedInstanceState)

	fastAdapter.getExpandableExtension().apply {
		//isOnlyOneExpandedItem = true
	}
	
And my items look like following:

    class Item(
        val data: TopData,
        val childItems: MutableList<ChildItem>
	) : AbstractItem<Item.ViewHolder>(), IExpandable<Item.ViewHolder> {
		// ...
	}
	
	class SubItem(
        val data: SubData,
        val childItems: MutableList<SubSubItem>
	) : AbstractItem<SubItem.ViewHolder>(), IExpandable<SubItem.ViewHolder> {
		// ...
	}
	
	class SubSubItem(
        val data: SubSubData
	) : AbstractItem<SubSubItem.ViewHolder>(), IExpandable<SubSubItem.ViewHolder> {
		// ...
	}

**Comment by mikepenz** [comment] 2020-03-15 14:59
@MFlisar this functionality is currently not supported and was actually never added due to it's complexity of supporting. 

one of the utils may allow you to build that, but I am not sure about if we should have this in the core / maintain this over time

**Comment by MFlisar** [comment] 2020-03-15 17:32
> this functionality is currently not supported
The functionality of having expandable items with a depth > 2?

I wonder why the demo uses more levels and works correctly (at least when it comes to collapsing all sub items if the parent is collapsed). I use the `IExpandable` interface and the demo works with `AbstractExpandableItem` but this should not make a difference

**Comment by mikepenz** [comment] 2020-03-15 17:49
oh. then it was added at some point. I have to be honest. I didn't check the code specifically after you reported, believing the report was checked with the sample app. 

could it be that the parent / child binding is not properly set up in your item? 
E.g.: a child does not refer it's parent properly?

**Comment by MFlisar** [comment] 2020-03-15 17:59
In the moment you wrote it I saw it... That was the reason, on of my child items was missing this.

How about supporting `isOnlyOneExpandedItem` not only at the lowest level? Is this something you think that should be added?

**Comment by mikepenz** [comment] 2020-03-21 16:30
Could you specify the usecase a little bit more which you'd hope to cover with this?

not sure about the complexity / if we should add this at the moment. 

And I suppose you still could get this into your project without a change in the main library?

**Comment by mikepenz** [comment] 2020-04-04 13:44
Please report back so we can see on how we can move forward with that or if we can close this issue :)

**Comment by MFlisar** [comment] 2020-04-08 09:56
My use case is following:

I want to allow one expandable item at each hierarchy level only so the behaviour would be like following:

**State 0**

- Top 1
   - Sub 1.1
     - SubSub 1.1.1
     - SubSub 1.1.2
     - SubSub 1.1.3
   - Sub 1.2
 - Top 2

**Action: User click Sub 1.2 -> Sub 1.1 gets collapsed automatically**

**State 1**

- Top 1
   - Sub 1.1
   - Sub 1.2
     - SubSub 1.2.1
     - SubSub 1.2.2
     - SubSub 1.2.3
 - Top 2

**Action: User click Top 2 -> Top 1 (incl. all subs) get collapsed automatically**

**State 2**

- Top 1
- Top 2
  - Sub 2.1
  - Sub 2.2

**Comment by mikepenz** [comment] 2020-04-08 10:01
but that would always depend per level so basically you want the expandable per level handled but ignore top level things e.g. sub.1.1 will be collapsed, but no sub section which may be opened in top 2 right?

**Comment by MFlisar** [comment] 2020-04-08 10:10
Logic would be per level (incl. all sub levels). Logic is nothing more than following:

If item get expanded collapse ALL items (incl. items underneath) that are at the same hierarchy level and are currently expanded - this rule alone would have all the side effects shown in my example.

In other words the following rules are true:
* only 1 item at level top can be opened at the same time
* only 1 item at level sub can be opened at the same time
* only 1 item at level subsub can be opened at the same time
* and so on...

This list shows why I think this logic fits into `isOnlyOneExpandedItem` for multi level lists

**Comment by mikepenz** [comment] 2020-04-08 10:12
but what I mean is that this can not (or should not) span across all entries at this particular level over all parents. that logic would be a real pain to maintain :D

**Comment by MFlisar** [comment] 2020-04-08 10:15
Not sure where we miss each other - at one particular level  only 1 item can be expanded. There list in my last post describes the rules that are valid for all items (and not underneath it's parents only)

**Comment by mikepenz** [comment] 2020-04-08 10:17
- Top 1
   - Sub 1.1
     - SubSub 1.1.1
     - SubSub 1.1.2
     - SubSub 1.1.3
   - Sub 1.2
 - Top 2
   - Sub 2.1
     - SubSub 2.1.1
     - SubSub 2.1.2
     - SubSub 2.1.3
   - Sub 2.2




E.g. if `Sub 1.2` get's opened. it will collapse 1.1 but leave Sub 2.1 alone

**Comment by MFlisar** [comment] 2020-04-08 10:21
Your situation is not possible because opening top2 will already close top1 (incl. all sub items).  I think the comlpexity you think about is not needed.

**Comment by mikepenz** [comment] 2020-04-11 11:58
So I just tried what you want to achieve in the sample app. and It works perfectly fine. so maybe some linking between parent and child is still not set-up properly?

You can try it in the `AdvancedActivity` using this branch: https://github.com/mikepenz/FastAdapter/commit/0d6c92108a9b377f326c95fa42c53daca08c9568

**Comment by MFlisar** [comment] 2020-04-15 12:08
I needed to change the setup a little to get this working with the current release AS version but I could test your demo now and it seems to work as expected - I will check if I still miss something in my code by comparing it with your example. Sorry for the inconvenience.

**Comment by MFlisar** [comment] 2020-04-17 07:48
I did see the issue again and now tried to reproduce it in your example again and "succeeded". Please try following:

* open "B - Test 6"
* open "B - SubTest 7"
* open "C - Test 51"

What you see is that "B - Test 46", "B - Test 47" and "B - Test 48" (items of the top level) will vanish in this case.

**Comment by mikepenz** [comment] 2020-05-09 14:02
Which sample did you use for this? 
Not really sure if I can see this

**Comment by mikepenz** [comment] 2020-05-30 07:53
If you have more information please let me know. I had a look but couldn't really reproduce. 

Closing for inactivity for the time being

**Closed by mikepenz** 2020-05-30 07:53 UTC
Labels: question
