### ISSUE TITLE
Single-selectable expandable adapter -> wrong selected item

### ISSUE THREAD

**Issue by WonderCsabo** [mikepenz/FastAdapter#218] opened 2016-09-22 16:16 UTC
Let's have a single-selectable, expandable adapter. 
If we select main items which are below expanded main items, wrong items will be selected.

This is because the `select()` method is called with the old position, but since then, a new item is expanded and the old is collapsed:

MainItem
SubItem
MainItem <- select this

MainItem
MainItem
SubItem

Now the `select()` method is called, but with `position = 2`, which is the old position of the second MainItem. Because of this, the last SubItem will be marked as selected instead of the MainItem.

**Comment by mikepenz** [comment] 2016-09-24 18:55
I can't reproduce this issue. If I add the following to the `ExpandableSampleActivity` It will output the correct positions:

```java
fastItemAdapter.withOnClickListener(new FastAdapter.OnClickListener<IItem>() {
            @Override
            public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
                if(item instanceof  SimpleSubItem) {
                    Log.e("WTF", ((SimpleSubItem) item).name + "  -  " + position);
                }
                return false;
            }
        });
```

**Comment by mikepenz** [comment] 2016-09-24 19:20
as an alternative you will be able to get the position of an item by it's identfier like this
```
        fastItemAdapter.select(fastItemAdapter.getPosition(101));
```

in v2.x

**Comment by WonderCsabo** [comment] 2016-09-24 19:44
I will try to create a reproducing sample project next week.

**Comment by mikepenz** [comment] 2016-09-24 19:50
thank you

**Comment by WonderCsabo** [comment] 2016-09-27 15:58
@mikepenz i created the sample project, you can check it out [here](https://github.com/WonderCsabo/FastAdapter_218).

**Comment by mikepenz** [comment] 2016-10-06 15:05
In general the problem is very easy to describe. A `FastAdapter` will always have to handle all types of items provided to it via various `ItemAdapter`s . You can type a `FastAdapter` and you can type a `ItemAdapter` but you will always have to make sure that you follow this simple rule:

**FastAdapter**
- it's type has to be the common type accross all the items provided for the `ItemAdapter`s
**ItemAdapter**
- It's type has to be the common type used within this `ItemAdapter`



This means you can solv eit via the following:
```java
public class MainActivity extends AppCompatActivity {

    FastItemAdapter<GenericAbstractItem> fastItemAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        fastItemAdapter = new FastItemAdapter<>();
        fastItemAdapter.withSelectable(true);
        fastItemAdapter.withSelectWithItemUpdate(true);
        fastItemAdapter.withOnlyOneExpandedItem(true);

        for (int i = 0; i < 10; i++) {
            fastItemAdapter.add(new SampleItem(String.valueOf(i))
                    .withSubItems(Collections.singletonList(new SampleSubItem("expanded: " + i))));
        }

        RecyclerView recyclerView = (RecyclerView) findViewById(R.id.recyclerView);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(fastItemAdapter);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.menu, menu);

        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        GenericAbstractItem next = fastItemAdapter.getSelectedItems().iterator().next();
        Toast.makeText(this, next.getModel().toString(), Toast.LENGTH_SHORT).show();

        return true;
    }
}
```

**Comment by WonderCsabo** [comment] 2016-10-07 09:02
This is not really a solution for me. 😢  You just changed the type of the returned item from `fastItemAdapter.getSelectedItems().iterator().next()`, and also the generic type parameter of the adapter, right?

This way the crash indeed does not occurs, but i will still get the wrong item.
Are you sure you understood the problem? Maybe it was not clear.

The problem is that i indeed should have get one of the top-level items as selected, but fastadapter wrongly returns a subitem as selected.

**Comment by WonderCsabo** [comment] 2016-10-07 09:06
Please try the sample app, i wrote steps to reproduce the problem. You selected the top level items in the sample app, and it still returns the subitem as selected, however the subitems were never selected actually, only the top-level ones. I debugged through the code, and i think the problem is that fastadapter selects a wrong item, because of the collapsing the indices are changing.

**Comment by mikepenz** [comment] 2016-10-07 09:27
ah you were referring to something else. I just debugged the crash, and fixed it. 

I will have another look

**Comment by WonderCsabo** [comment] 2016-10-07 09:36
Thank you!

**Comment by mikepenz** [comment] 2016-10-09 19:57
@WonderCsabo I just added to have a colored background for the selected item. and I was able to reproduce. it make sense at a closer look. No idea why nobody else realized this until now. 

The problem happens here:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L441
we expand the item first and then set the selection. Thank you for showing this. It will be fixed in v2.0.0 

best regards.

**Comment by mikepenz** [comment] 2016-10-09 20:11
[FastAdapter_218-fix.zip](https://github.com/mikepenz/FastAdapter/files/518527/FastAdapter_218-fix.zip)

Adjusted your project to work with the new v2.0.0 (changed the items to use the new `ISubItem` interface, and fixed the wrong `isAutoExpand` method)

**Closed by mikepenz** 2016-10-09 20:11 UTC
Labels: question

**Comment by WonderCsabo** [comment] 2016-10-10 07:36
Thanks for the fix and also for updating the sample project! I guess nobody
used this set up before, that is why it remained unnoticed. ☺️
