### ISSUE TITLE
NPE in IdDistributor.checkId

### ISSUE THREAD

**Issue by stevesea** [mikepenz/FastAdapter#334] opened 2017-02-13 06:53 UTC
I haven't been able to reproduce this, but here's the stack track reported via Crashlytics:

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'long com.mikepenz.fastadapter.IIdentifyable.getIdentifier()' on a null object reference
 Raw Text
com.mikepenz.fastadapter.utils.IdDistributor.checkId (IdDistributor.java:49)
com.mikepenz.fastadapter.utils.IdDistributor.checkIds (IdDistributor.java:24)
com.mikepenz.fastadapter.adapters.ItemAdapter.set (ItemAdapter.java:250)
com.mikepenz.fastadapter.adapters.ItemAdapter$ItemFilter.publishResults (ItemAdapter.java:523)
android.widget.Filter$ResultsHandler.handleMessage (Filter.java:282)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7229)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

It seems like the stack trace would happen if an item in the adapter was null. 

But, I'm not sure when/why that'd happen... or, why it'd happen so infrequently (about 3 instances over last 2-3 months of hundreds of users)

I'm using version 2.1.0 of FastAdapter, my code is available at https://github.com/stevesea/Adventuresmith/tree/0.18.0

**Comment by mikepenz** [comment] 2017-02-13 08:30
@stevesea hmmm sounds like some concurrent issue.

**Comment by FabianTerhorst** [comment] 2017-02-13 11:02
@stevesea why you are using an own AtomLong object in your code?

**Comment by mikepenz** [comment] 2017-02-13 11:04
@FabianTerhorst the issue seems to be a concurrent issue caused by the `ItemFilter`, which is the only description why it would be able to set a "null" list to the adpater

**Comment by stevesea** [comment] 2017-02-13 20:15
@mikepenz how would you recommend synchronizing access to the FastAdapter? Do I need to only worry about modifications to the FastAdapter's item list, or should applying a filter also be done while holding a lock?

**Comment by mikepenz** [comment] 2017-02-13 20:16
@stevesea I think that's something I should figure out inside the filter code.

**Comment by stevesea** [comment] 2017-02-24 00:41
I was able to reproduce the problem...  To get things to behave badly, seems like I have to do some filtering, then exit filtering. After that, I sometimes see odd lagginess of my recyclerview when adding new items, and sometimes see the crash.

After playing around with it a bit... I did see that I was doing something probably very weird -- There are times I wanted to retain the filter, but also add more items to the result list (the code would set the FastAdapter's filter to null, add items, then restore the previous filter). Once I changed around my code to prevent the user from causing that to happen, things behaved much better.

**Comment by mikepenz** [comment] 2017-02-24 16:57
@stevesea have you found what could be the cause? I have a hard time reproducing this. Perhaps you can provide a sample to showcase the issue

**Comment by stevesea** [comment] 2017-02-24 18:40
@mikepenz I'll try tweaking the sample application and see if I can reproduce it there.

**Comment by mikepenz** [comment] 2017-02-24 18:44
awesome. thanks

**Comment by mikepenz** [comment] 2017-03-13 12:26
@stevesea any update?

**Comment by stevesea** [comment] 2017-03-15 07:05
Apologies for the delay, I've been on vacation. I haven't been able to reproduce the issue with modifications to the sample app yet. 

I did some changes to my app that _may_ have improved stability. I pushed the release a couple weeks ago, and the crash hasn't appeared in my Crashlytics reports with the latest release.

I ended up hitting it with a big hammer first... Wrapping all access to my FastAdapters in synchronized blocks [changeset](https://github.com/stevesea/Adventuresmith/commit/eb292ebcfab63c8d2d2575938e7440d8084d3dbb )

But, there was still at least 1 crash event after those changes made it into a release. After experimenting in my app some more, I saw the odd behavior and crash I mentioned in my last comment in this thread. That made me decide to make this [changeset](https://github.com/stevesea/Adventuresmith/commit/7a097b17b6ae6ade085566ce66147fbd4b73ae11) 
The interesting lines there are the changes to AdventuresmithActivity.kt around line 350. 

```
```

**Comment by mikepenz** [comment] 2017-03-15 09:08
@stevesea thank you very much for the detailed report. I think this sounds like the `FastAdapter` itself is less the problem but more the way how it was used / how the items were defined. 

I'll close this for now, and we should keep an eye on this

**Closed by mikepenz** 2017-03-15 09:08 UTC
Labels: bug
